# Generated by Django 4.1.6 on 2023-02-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'registration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_needed', models.IntegerField(blank=True, null=True)),
                ('hours_rendered', models.IntegerField(blank=True, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=20, null=True)),
                ('room_code', models.CharField(blank=True, max_length=50, null=True)),
                ('room_name', models.CharField(blank=True, max_length=100, null=True)),
                ('scholar_year', models.IntegerField(blank=True, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'scholar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceHourListing',
            fields=[
                ('serv_hours_id', models.IntegerField(primary_key=True, serialize=False)),
                ('serv_hours_date', models.DateField(blank=True, null=True)),
                ('serv_hours_time', models.TimeField(blank=True, null=True)),
                ('serv_hours_loc', models.CharField(blank=True, max_length=255, null=True)),
                ('serv_hours_slot_count', models.IntegerField(blank=True, null=True)),
                ('serv_hours_task', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'service_hour_listing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('user_password', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
